accumulate_grad_batches: 1
batch_size: 16
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: REDataset
data_dir: ./dataset/ske
gpus: 0,
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_class: RELitModel
logger: true
lr: 3.0e-05
max_epochs: 5
max_seq_length: 128
# here set max steps
max_steps: 32
max_time: null
min_epochs: null
min_steps: null
model_class: BertForNER
model_name_or_path: bert-base-chinese
model_type: bert
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
optimizer: AdamW
overfit_batches: 0.0
overwrite_cache: false
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 42
stochastic_weight_avg: false
sync_batchnorm: false
task_name: ner
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
wandb: false
weight_decay: 0.01
weights_save_path: null
weights_summary: top
