accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
data_class: REDataset
data_dir: ./dataset/ske
default_root_dir: null
deterministic: false
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 0,
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_class: SEQLitModel
load_checkpoint: null
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 5.0e-05
max_epochs: 1
max_seq_length: 128
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_class: BertForRelationClassification
model_name_or_path: bert-base-chinese
model_type: bert
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
optimizer: AdamW
overfit_batches: 0.0
overwrite_cache: false
path: /home/xx/OpenUE-openue_pytorch/output/epoch=0-Eval/f1=0.91.ckpt
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
seed: 42
stochastic_weight_avg: false
sync_batchnorm: false
task_name: seq
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
wandb: false
weight_decay: 0.01
weights_save_path: null
weights_summary: top
